package:
    name: zmq_h5_writer 
    version: 0.0.1

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - make
        - gcc
        - cppzmq =4.2.1
        - hdf5 =1.8.17
        - boost =1.61.0

    run:
        - cppzmq =4.2.1
        - hdf5 =1.8.17
        - boost =1.61.0


about:
    summary: "C++ implementation of a ZMQ to H5 writer."

