package:
  name: cadump
  version: 0.0.6

source:
    path: ..

build:
  entry_points:
    - cadump_server = cadump.cadump:main

requirements:
  build:
    - python
    - data_api
  run:
    - python
    - data_api