package:
  name: epics-writer
  version: 0.0.1

source:
    path: ..

build:
  noarch: python
  entry_points:
    - epics-writer = epics_writer.start:main

requirements:
  build:
    - python
  run:
    - python
    - data_api >=0.7.6
    - requests
    - pika
